-- Step 1: 
USE ROLE ACCOUNTADMIN;

-- Step 2: Create warehouse, DB, schema, role
CREATE WAREHOUSE IF NOT EXISTS DBT_WH WITH WAREHOUSE_SIZE = 'X-SMALL';
CREATE DATABASE IF NOT EXISTS DBT_DB;
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- Step 3: Grant privileges
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
GRANT ROLE DBT_ROLE TO USER tbonesteak5372;
GRANT ALL ON DATABASE DBT_DB TO ROLE DBT_ROLE;

-- Step 4: Switch to your custom role (AFTER it's been granted)
USE ROLE DBT_ROLE;

-- Step 5: Create schema and assign table creation rights
CREATE SCHEMA IF NOT EXISTS DBT_DB.DBT_SCHEMA;
GRANT USAGE ON SCHEMA DBT_DB.DBT_SCHEMA TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA DBT_DB.DBT_SCHEMA TO ROLE DBT_ROLE;
